base: 'https://typo3-project.ddev.site/'
dependencies:
  - test/my-site-package
  - typo3/form
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: 'Example site'
